apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-world-deployment
  labels:
    app: go-hello-world-app
    backstage.io/kubernetes-id: go-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hello-world-app
  template:
    metadata:
      labels:
        app: go-hello-world-app
        backstage.io/kubernetes-id: go-hello-world
    spec:
      containers:
        - name: go-hello-world
          image: quay.io/keranyang/go-hello-world:v1.0.1
          imagePullPolicy: Always